### ISSUE TITLE
Issues when using fields instead of properties in model as HttpPost payload

### ISSUE THREAD

**Issue by leppie** [domaindrivendev/Ahoy#123]
Say you have:

```
public class Foo
{
   public string Bar;
   public string Baz; 
}
```

and your operation is:

```
public bool Action(Foo foo) {... }
```

Seems to fail rendering it correctly.

Making the fields, properties instead, works, as well as using `[FromBody]`  on `foo`

**Comment by domaindrivendev** [comment]
I can't repro your issue with fields - i.e. when I include a public field (as opposed to property), I'm seeing it documented as expected.

You will need to use [FromBody] though. In fact, explicit parameter bindings in general are required for SB to generate Swagger documentation. This is because Swagger doesn't support the notion of an "open" parameter that can be provided through ANY of the HTTP input mechanisms (query, body, header etc.), which is essentially what you're doing when you omit the explicit binding. See #47 for more discussion on this.

**Comment by leppie** [comment]
Perhaps it got fixed along the lines. Will report if I come across it again.
