### ISSUE TITLE
[Question] HttpGet

### ISSUE THREAD

**Issue by XcoderTeam** [domaindrivendev/Ahoy#169]
Hi,

Quick question regarding the swagger, Why above method is appear on swagger docs?
Since this below method it should be method that return a view?
At the moment i use IgnoreApi to disabled the method in docs list.

`[Route("features")]
        [HttpGet]
        public IActionResult Features()
        {
            ViewBag.Menu = "Feature";
            return View();
        }`

**Comment by andyalm** [comment]
Swashbuckle works by reflecting over your code using ApiExplorer. Since some API's make use of IActionResult return types, Swashbuckle does not know from reflection whether this will return a view or something else like a JsonResult. It does not actually run your code as that would be very complicated. Explicitly telling Swashbuckle to ignore that controller or action is the best you can do.
