### ISSUE TITLE
Swagger definition not using int16 for path parameter

### ISSUE THREAD

**Issue by chrisklepeis** [domaindrivendev/Ahoy#178]
```
        [SwaggerOperation("CreateJwtToken")]
        [ProducesResponseType(typeof(Token), (int)HttpStatusCode.OK)]
        [HttpPost("api/auth/generatetoken/{username}/{password}/{businessEntityId}")]
        [AllowAnonymous]
        public IActionResult Post(string username, string password, short businessEntityId)
        ....
```

The swagger definition has businessEntityId as a int32.... I'm not sure how to get it to define as a int16.

From looking around, I thought maybe {businessEntityId:int16} would work, but that just throws errors.

Is there anyway to accomplish this with the latest prerelease (using asp.net core)?

**EDIT**

Another issue I'm seeing is that my response model properties are being marked as optional, even though I have the [Required] attribute on them.

**Comment by SimonTouchtech** [comment]
Swashbuckle explicitly sets shorts to int32, see https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Generator/SchemaRegistry.cs#L230 

My guess as to why this is done is that int16 is not a "known format" of Swagger but int32 is, see http://swagger.io/specification/#dataTypeFormat. I'm not associated with this project so in the end I am just guessing what @domaindrivendev thinks, but I believe this behavior is intentional and I agree that it's the best way to handle it.

If you really want to use int16 as format it's perhaps possible to use a custom schema, but I'm not sure how to do that.

**Comment by chrisklepeis** [comment]
Closing this issue, as it appears to be a limitation of the swagger spec
