### ISSUE TITLE
Response Codes not interpreted from the XML

### ISSUE THREAD

**Issue by YZahringer** [domaindrivendev/Ahoy#24]
The node <response ... /> is not interpreted from the XML Comments file.

I think is a missing method to use and read Swashbuckle.Swagger.XmlComments.ApplyXmlActionComments.ResponseExpression.

Best regards,
Yann

**Comment by domaindrivendev** [comment]
There's really not enough info here for me to understand your issue. Can you elaborate with some sample code?

**Comment by YZahringer** [comment]
C# response code comments not generated in swagger documentation:
```xml
/// <response code="200">Login success</response>
/// <response code="400">Invalid or missing parameters in request</response>
```

I write a OperationFilter to make this, but is a workaround:
```cs
public class ApplyXmlResponseComments : IOperationFilter
{
    private const string MethodExpression = "/doc/members/member[@name='M:{0}.{1}{2}']";
    private const string ResponseExpression = "response";

    private readonly XPathNavigator _navigator;

    public ApplyXmlResponseComments(string filePath)
    {
        _navigator = new XPathDocument(filePath).CreateNavigator();
    }

    public void Apply(Operation operation, OperationFilterContext context)
    {
        var controllerActionDescriptor = context.ApiDescription.ActionDescriptor as ControllerActionDescriptor;
        if (controllerActionDescriptor == null) return;

        var methodXPath = GetMethodXPath(controllerActionDescriptor.MethodInfo);
        var methodNode = _navigator.SelectSingleNode(methodXPath);
        if (methodNode == null)
            return;

        var responseNodes = methodNode.Select(ResponseExpression);
        if (responseNodes.Count > 0)
            operation.Responses.Clear();
            
        foreach (XPathNavigator responseNode in responseNodes)
        {
            var code = responseNode.GetAttribute("code", string.Empty);
            if (string.IsNullOrEmpty(code) ||
                operation.Responses.ContainsKey(code))
            {
                continue;
            }
            var isSuccessResult = int.Parse(code) < (int) HttpStatusCode.BadRequest;
                
            var description = responseNode.ExtractContent();
            var schemaType = !isSuccessResult ||
                                context.ApiDescription.ResponseType == null ||
                                context.ApiDescription.ResponseType == typeof (void)
                ? null
                : context.SchemaRegistry.GetOrRegister(context.ApiDescription.ResponseType);

            operation.Responses.Add(code, new Response {Description = description, Schema = schemaType});
        }
    }

    private static string GetMethodXPath(MethodBase methodInfo)
    {
        var typeLookupName = methodInfo.DeclaringType.XmlLookupName();
        var actionName = methodInfo.Name;

        var paramLookupNames = methodInfo.GetParameters()
            .Select(paramInfo => paramInfo.ParameterType.XmlLookupNameWithTypeParameters())
            .ToArray();

        var parameters = (paramLookupNames.Any())
            ? $"({string.Join(",", paramLookupNames)})"
            : string.Empty;

        return string.Format(MethodExpression, typeLookupName, actionName, parameters);
    }
}
```

**Comment by domaindrivendev** [comment]
You should use Swagger annotations to provide response codes:

        [SwaggerResponse(404, "Cart not found")]
        [HttpGet("/carts/{id}")]
        public Cart GetById(int id)

By design, this can no longer be done using XML comments. Here's the rationale ...

There's an impedance mismatch between "code comments" (i.e. Xml comments) and description of a HTTP/REST based API. The former describes implementation details (i.e. controllers, c# types etc.) encapsulated by the API whereas the latter describes the actual API and how it should be consumed. The introduction of non-standard attributes to Xml comments only further highlights the existence of this mismatch.

This presents a problem because the "intent" becomes blurred. For example, a developer may provide implementation detail in Xml comments that's only intended for an internal audience. This is perfectly understandable, particularly if they're unfamiliar with Swashbuckle. After-all, this is what Xml comments are intended for.

However, they sure do provide a convenient way to assign the "textual" Swagger properties. For the more structured properties like response codes, operation id's and even examples, I think custom attributes are a better approach for the following reasons.

1. They explicitly indicate the intent (i.e. API documentation) as opposed to piggy-backing onto a feature that's meant for a different purpose.
2. They don't force the "Xml comments" practice onto development teams (I for one favor expressive code over comments).

So, with all that said, I'm happy to continue support for "descriptive" properties through the existing standard Xml attributes, purely for the convenience it affords (assigning paragraphs of text to an attribute property would be tricky). However, I've removed support for the non-standard "response" attribute in favor of the SwaggerResponse attribute.

**Comment by bluemmc** [comment]
The problem with the SwaggerResponse attribute is that it introduce lots of dependencies on swagger inside the controller code. It is best to have loose coupling with as few dependencies as possible - especially on implementation details like documentation tools and especially dependencies that touch a  large number of places in the code. Hence there are sound reasons to use the XML response comments that swagger supports (and other documentation tools can support as well). Please reconsider!

**Comment by TWolverson** [comment]
Could you please amend the repository documentation to no longer refer to this practice, if it doesn't work anymore?
