### ISSUE TITLE
Inject a custom stylesheet?

### ISSUE THREAD

**Issue by antonkallenberg** [domaindrivendev/Ahoy#32]
Is there a way to inject a custom stylesheet like in Swashbuckle for WebAPI?

``` csharp
.EnableSwaggerUi(x =>
            {
                x.InjectStylesheet(typeof(AppHost).Assembly, "MyProject.Api.Resources.Swagger.UiCustomization.css");
            });
```

**Comment by domaindrivendev** [comment]
In this version, I've changed the approach to UI customization. Rather than maintaining a whole set of abstractions for injecting assets you simply override the out-of-the-box index.html with you're own custom version which you can go ahead and customize any way you see fit.

You do this by placing a copy of the [swagger-ui index.html](https://github.com/swagger-api/swagger-ui/blob/v2.1.3/dist/index.html) under "wwwroot/swagger/ui".

If you have the static file middleware enabled (e.g. UseStaticFiles), this should get picked up instead of the out-of-the-box version. Be sure to update the discovery url to that of your service.

Checkout the CustomizedUi sample for reference.

**Comment by antonkallenberg** [comment]
Awesome! Thanks, I'll give it a try!
