### ISSUE TITLE
No apparent way to add Operation Response Headers

### ISSUE THREAD

**Issue by michaelrgilbert** [domaindrivendev/Ahoy#55]
I tried to create a custom attribute (ResponseHeaderAttribute) which I look for with an OperationFilter and then add a new Header object to the operation.Responses.Headers collection (for the appropriate response), however I find there is no "name" attribute on the Header class and the Headers collection is just a List<Header> - I had expected a Dictionary<string, Header> and assumed that the Header "name" would be the key, but it appears not.  How should I add, for example an ETag header to the 201 Response from a POST?

Regards,

Michael R. Gilbert

**Comment by senj** [comment]
I have the same question the other way round, I want to add a header to my request. I also tried adding an attribute with OperationFilter but there is no "value".

**Comment by krswope** [comment]
Bump.  I would also love to know how to add response headers.

**Comment by kyschouv** [comment]
The issue here is that the `Headers` collection on `Response` is an `IList<Header>`, compared to `Swashbuckle's IDictionary<string, Header>`. Because of this, the header name isn't available, and it doesn't serialize correctly. Changing it in [SwaggerDocument.cs](https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Generator/SwaggerDocument.cs) should fix the issue.

**Comment by kyschouv** [comment]
I submitted a pull request that should at least fix adding this to the swagger document. #73 

SwaggerUI seems to be on an older version though, so the UI doesn't display the response headers.
