### ISSUE TITLE
See tags in XML comments not handled 

### ISSUE THREAD

**Issue by bluemmc** [domaindrivendev/Ahoy#57]
Ahoy does not resolve a see tag in the XML comments correctly as shown in the example below. Instead of showing the reference endpoint it displayes the string "{X:XXX.XXX.XXX.Version}" inline in the generate HTML text
```
/// <summary>
///  Bla. bla. use the <see cref="Version"/> method instead.
/// </summary>
```

**Comment by domaindrivendev** [comment]
This behavior is by design.

SB leverages XML comments as they're a convenient place to provide text-based descriptions for your API. However, it doesn't (and IMO shouldn't) provide all of the functionality that you from their traditional usage. The audience of XML comments is typically other C# developers either consuming or maintaining the code. However, the audience of Swagger is API consumers that are only concerned with your interface in terms of HTTP / REST and have no desire to see details of the inner workings and C# implementation.

**Comment by ataraxia89** [comment]
4 people like the suggestion, 5 people dislike the answer...

There is no need to detail "inner workings", why can the tags not just be replaced at runtime with the referenced object's name? Or at the very least, insist on this syntax <see cref="Version">MyVersionName</see> and replace the tag with the name "MyVersionName"?
