### ISSUE TITLE
Versioning is ignored

### ISSUE THREAD

**Issue by ericwj** [domaindrivendev/Ahoy#70]
I'm using a pull from just today `2c007dcc`. The API version is ignored by Swagger UI.

``` CSharp
services.AddSwaggerGen(options => { Version = "1.0" });
...
app.UseSwaggerUI(swaggerUlr: "/swagger/1.0/swagger.json");
```

I found it odd if I specify version `1.0` manually that there is no longer a `v` in front of the version in the swagger.json URL. Also, Swagger UI will completely ignore the non-default version. Ideally, shouldn't `UseSwaggerUI` not also accept a template for `swaggerUrl` and automatically pick the latest? 

Not sure what the convention or specification is here. However, the UI and the API spec use/are at different URLs even after manually correcting by providing the `swaggerUrl` argument. Browsing to [/swagger/ui/index.html](), Swagger UI will happily put [/swagger/v1/swagger.json]() in the box at the top of the page, although my swagger.json is actually located at [/swagger/1.0/swagger.json]().

Plus, if I type to correct the URL and refresh, it puts back `v1` and crash with a 500...
`SwaggerProvider.cs`
`34.                throw new UnknownApiVersion(apiVersion);`
It does so both in production and in development. Should that be wrapped somewhere and return 404 if `!IHostingEnvironment.IsDevelopment()`?

**Comment by domaindrivendev** [comment]
The semantics have changed a little since this issue was created. First, you define one or more Swagger documents, providing a document name / identifier, info and inclusion criteria for . You can check this out in the example site

**Comment by domaindrivendev** [comment]
The semantics have changed a little since this issue was created. First, you define one or more Swagger documents, providing a document name / identifier, info and inclusion criteria for each. You can check this out in the example site:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/MultipleVersions/Startup.cs#L28

Then, you configure swagger-ui to power documentation from one or more of these documents. providing the corresponding endpoint:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/MultipleVersions/Startup.cs#L60

Using the sample app, I replaced the document identifiers to be "1.0" and "2.0" and it all worked as expected. So, I believe this issue is resolved.
