### ISSUE TITLE
Cannot access ui or json

### ISSUE THREAD

**Issue by mburumaxwell** [domaindrivendev/Ahoy#8]
Hello,

I tried adding the package via nuget but I could not access the extension methods for Swagger
```json
"Swashbuckle": "6.0.0-beta1"
```
So I decided to clone the repo locally the add it to my solution as a project and to my vNext project as a dependency. The solution built and the vNext website run. Unfortunately, I cannot access /swagger/ui neither can I access /swagger/v1/swagger.json. Here is my setup
Inside the ConfigureServices method
```c#
// Add swagger documentation
services.AddSwagger(s => {
    s.SwaggerGeneratorOptions(c => {
        s.SwaggerGeneratorOptions.Schemes = new[] { "http", "https" };
        s.SwaggerGeneratorOptions.SingleApiVersion(new Swashbuckle.Swagger.Info {
            Version = "v1",
            Title = "My vNext Api",
            Description = "some placeholder for description",
            TermsOfService = "some terms if need be"
    });

    s.SchemaGeneratorOptions.DescribeAllEnumsAsStrings = true;
});
```
Inside the Configure method
```c#
// Add Swagger Docs
app.UseSwagger();
app.UseSwaggerUi();
```

I put breakpoints to ensure that they initialized and yes they did. Any guidance?

**Comment by batesiiic** [comment]
I have gone down a very similar path as you except I gave up trying to use the latest commit since getting the beta 5 ASP.NET stuff working with azure proved too difficult for now (so I'm back to simply using swashbuckle 6.0.0-beta1 with ASP.NET beta 4). I haven't figured out how to get the UI to show up, but I have successfully gotten the swagger doc to show up. I found that for some weird reason if I start up my website locally in IIS (or even hit it from Azure) immediately after starting/publishing it, I will get a 404 error. However, if I hit my API first, then go to the /swagger/v1/swagger.json, the json shows up as expected. Note that you must hit the API first after starting the website, otherwise you won't get the json to generate until the site is restarted and the API is hit before the swagger call is attempted.

My current setup is to have a controller specifically hosting a swagger API that returns the documents that I generate manually by calling the ISwaggerProvider in Swashbuckle, which will generate correctly no matter the state.

Hopefully this is the same issue you are seeing and you can at least generate json. I'm still pursuing why the UI doesn't show up correctly (something about looking for an embedded asset in SwaggerUiHandler.RouteAsync), but will post any more findings here.

**Comment by choudeshell** [comment]
If you have cloned the repository, you will be able to step-through the code. Please read http://blogs.msdn.com/b/webdev/archive/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015.aspx , specifically the section **'Using the local source code instead of the official binaries'**.

Add a break point in the **Invoke** method, in either of the middlware, **'SwaggerUiMiddleware.cs**' or **SwaggerDocsMiddleware.cs'** and see why it isn't working. Most likely you have a middlware handling the request before it gets to the Swagger middleware or it is not matching.

**Comment by batesiiic** [comment]
I was able to get beta5 working with Azure so I worked with this more and found that I was missing 

```
<modules runAllManagedModulesForAllRequests="true" />
```

from my web.config. Adding this in (taken directly from the Swashbuckle test sites) fixed my issue so everything works as expected now. The full config looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>
</configuration>
```

Removing that config value from the test sites will cause the same problem.

**Comment by mburumaxwell** [comment]
@batesiiic I also managed to get the json but the UI does not show up. The issue was that I called AddSwagger after AddMvc and UseSwagger after UseMvc. It was really stupid of me...

**Comment by mburumaxwell** [comment]
Hello,

I figured out what the problem is. You need to restore the bower packages for it to display the ui. There is only one bower package "swagger-ui". It contains the js and css that are referenced in SwaggerUi/index.html.
Everything on mine works seamlessly and beautifully now... So I can close the case. Thank you for your help
