### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by cwe1ss** [domaindrivendev/Ahoy#85]
Hi @domaindrivendev,

since this project is becoming a very important dependency for many people, it's important to keep it up-to-date. There hasn't been much activity lately, so I'm wondering how we can help you? 

Do you plan to improve this project during the next days/weeks (to get it compatible with RC2)?
Would you consider adding additional contributors?
What's your general plan for this project?

It would be great if we could concentrate our efforts on this project - publishing a fork should be avoided if possible IMO.

Please don't take this as criticism - I understand how hard it is to find time for these projects!

thanks for the time you've already put into this!

**Comment by domaindrivendev** [comment]
Dup of #84

Looking at the various PR's, it looks like a lot of people are duplicating work - I also have a local RC2 branch in progress. My bad for lack of communication. With two small kids there just aint enough hours in the day - even to just get the appropriate communication out there :(

I won't be accepting any PR's that don't come with a green suite of tests so that makes #88 the likely candidate. I'm going to pull it down tomorrow and compare with my own local branch before merging one of them into master. Either way, I'm targeting 5/28 for an RC2 compatible release to Nuget. See the beta2 milestone here https://github.com/domaindrivendev/Ahoy/milestones. Note the revert to "beta" status - still lots of feature gaps and a config. API that will likely undergo change before we reach a stable release.

Thanks to everyone for chipping in. Please don't get disheartened if I'm slow to respond to PR's. So long as they include tests and a passing suite, I'll get always consider them and strive to respond as soon as I can.

I have one significant architectural refactor that I want to get done after the beta2 release. After this, I'll be looking to open up the project and add additional contributors. For anyone reading this, please let me know if you're interested?

Ahoy!

Richie
