### ISSUE TITLE
IActionResult and 204 response

### ISSUE THREAD

**Issue by svickers** [domaindrivendev/Ahoy#97]
In previous versions of swashbuckle, an action such as this would generate a 200 response in the swagger docs:

`        [HttpGet]
        public async Task<IActionResult> Empty()
        {
            return Ok();
        }`

In 6.0, the resulting swagger file specifies a 204 response:

`"get": {
        "tags": [
          "Values"
        ],
        "operationId": "ApiValuesGet",
        "produces": [
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        },
        "deprecated": false
      },`

The problem is, webapi actually returns a 200. When using a client generator like autorest, that means every call throws an exception because the response code is not what is expected.  In order to be compatible with clients we have out in the wild, I've decorated each method with:

        [SwaggerResponseRemoveDefaults]
        [SwaggerResponse(200)]

Not sure which is the correct way, domaindrivendev/swashbuckle#726 seems to indicate a 200 should be the default?

**Comment by domaindrivendev** [comment]
@rynowak - this is somewhat related to our discussion here https://github.com/aspnet/Mvc/issues/4823

Looking at the following casee







In the cases where the action returns an ambiguous response type (e.g. IActionResult), AspNet defaults to a 200 response type at run-time. Swashbuckle should reflect this (as implementation is truth in it's world) but is currently getting confused between the ambiguous return type and the explicit void return type because both result in an empty SupportedResponseTypes collection on the ApiDescription.

Unless I'm missing something, I don't see anything on ApiDescription that would allow me to distinguish these cases. I could just

**Comment by domaindrivendev** [comment]
@rynowak - this is somewhat related to our discussion here https://github.com/aspnet/Mvc/issues/4823

Looking at the following cases

    public IActionResult DoSomething()
    {
        ....
    }

    public void DoSomethingElse()
    {
        ....
    }

AspNet Core will, by default, return a 200 for the former and a 204 for the latter. However, I can't reflect this behavior in the generated Swagger because, unless I'm missing something, ApiDescription provides no way to distinguish between the two - in both cases "SupportedResponseTypes" is empty.

I think this is an issue with the new ApiExplorer because it doesn't provide enough information to accurately describe default behavior. What's your thoughts, am I missing something?

**Comment by rynowak** [comment]
> AspNet Core will, by default, return a 200 for the former and a 204 for the latter.

This isn't true. The default is always 200. We used to (circa RC1 I believe) treat all `void`/`Task` (non-generic)-returning methods as a 204 which is a massive break with MVC's legacy. But this was changed a while ago.

When an `ObjectResult` with a `null` model object is returned, there is a formatter which will set the status code to 204. This includes cases like the following:
```
public object GetProductOrDefault(int id)
{
    return _db.Products.Where(p => p.Id == id).FirstOrDefault();
}
```
```
public IActionResult CreateProduct(Product product)
{
    ...
   return CreatedAtAction("GetProduct", new { id = product.Id }, null);
}
```

We could consider changing the default so that **everything** as a 200 unless otherwise specified if you'd prefer. It's simply not possible for us to have an understanding of what will happen in some pretty common cases.

**Comment by domaindrivendev** [comment]
Thanks for the quick response - this makes Swashbuckle's task a little easier as I can just default to 200 when ProducesResponseTypes is empty and that will be consistent with the runtime behavior.

The ObjectResult case is non-deterministic during Swagger generation (because it depends on runtime logic) and therefore the explicit attributes MUST be provided anyway to yield an accurate description.

**Comment by KennethRMason** [comment]
Referring to the Swashbuckle documentation (not Ahoy), it looks like you used to be able to include things like this in your XML doc block for an action:
        /// <response code="400">Request failed validation</response>
It seems like these would be a reasonable work around, for those of us returning IActionResult, or Task<IActionResult>.

However, it seems these tags aren't being picked up when using Swashbuckle with .Net Core.  I took a look at XmlCommentsOperationFilter, and indeed it doesn't seem to be picking these up.

What are your thoughts on using those xml doc blocks to solve the problem?  I'd like these to be picked up regardless, so I can describe the non-200/204 responses in the XML doc blocks.

**Comment by pwen090** [comment]
In asp.net core code such as:
```
[HttpPost]
public async Task<IActionResult> PostThing([FromBody] Thing thing)
{
     [...]
     return CreatedAtAction("GetThing", new { id = thing.Id }, thing);
}
```

This outputs a swagger definition with a 200 code. I am wondering what is the proper way to have the output swagger definition accurately represent the 201 created. I know you can do this with Swashbuckle such as ([SwaggerResponse(HttpStatusCode.Created,"Thing",typeof(Thing))]) but when trying to do this with asp.net core [ProducesResponseType(typeof(Thing),201)] it does not seem to properly honor the 201 and rather still is outputing for 200. I read this thread and similiar on asp.net core repo but not overly clear what was settled on as the proper way to handle this?

**Comment by svickers** [comment]
Closing because it looks like the default is back to 200 now.
