### ISSUE TITLE
"Microsoft.AspNetCore.Mvc" dependency brings kitchen sink, and is unneccessary

### ISSUE THREAD

**Issue by Ciantic** [domaindrivendev/Ahoy#98]
I'm developing a pure web api, the SwaggerGen and SwaggerUi has kitchen sink dependency, and also something that is not intended:

```
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0-rc2-final",
```

This makes no sense, Mvc includes the Core, and everything else, including Razor (views) etc. 

To make this lean, the SwaggerGen and SwaggerUi should not add `"Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final"` dependency, instead it should list Core and other smaller packages it actually uses in the Mvc.

E.g. for building a project.json without that big dependency, [project.json in my example project](https://github.com/Ciantic/AspNetApiMonolithSample/blob/master/src/Api/project.json), is built from smaller Mvc packages.

**Comment by rynowak** [comment]
:+1: I'll add that `Microsoft.AspNetCore.Mvc.ApiExplorer` is factored out into it's own package so that packages like Ahoy can have a lean set of dependencies.

If you get a chance to look at this one let me know ASAP if you run into any blocking issues because we're locking for the real 1.0.0 soon.

**Comment by domaindrivendev** [comment]
Good catch. Resolved with this commit https://github.com/domaindrivendev/Ahoy/commit/a3b0875e435e13196dd0982ad329cd13d4be46e5
